### ISSUE TITLE
사업프로그램 및 우선선발

### ISSUE THREAD

**Issue by ghost** [stcoss-ai/UNLV#8]
- 인공지능혁신융합대학 사업 프로그램에 무조건 참여한 학생들만 지원이 가능한건가요?(한번도 참여하지 않았다면 지원 자체가 불가능한 건지)
- 인공지능응용학과 우선 선발인가요?

**Comment by stcoss-ai** [comment]
안녕하십니까. 
혁신융합대학사업단 입니다.
질문해주신 내용 답변 드리겠습니다.

1. 동계 해외 단기 파견 학생 선발은 **인공지능혁신융합대학 사업 프로그램 참여 경력이 있는** 학생만 지원이 가능합니다.
2. 학과는 우선 선발 여부에 포함되지 않습니다. 

감사합니다.
